{{- if and (not .Values.homeAssistant.existingAutomationsConfigMap ) .Values.homeAssistant.automations }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-automations
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    helm.sh/resource-policy: keep
data:
  automations.yaml: |- {{ .Values.homeAssistant.automations | nindent 4 }}
{{- end }}
