{{- if and (not .Values.homeAssistant.existingConfigurationConfigMap ) .Values.homeAssistant.configuration }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    helm.sh/resource-policy: keep
data:
  configuration.yaml: |- {{ .Values.homeAssistant.configuration | nindent 4 }}
{{- end }}
