{{- if .Values.homeAssistant.owner.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-create-user-script
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
data:
  create_user.py: |
    import json
    from os import environ as env
    import requests


    class RunHomeAssistantOnboarding():
        """
        Runs through home assistant onboarding to create a new user and disable registration

        home assistant user onboarding urls found here:
        https://github.com/home-assistant/core/tree/dev/homeassistant/components/onboarding/views.py
        """
        def __init__(self):
            self.headers = {
              'Content-Type': 'application/json',
            }
            self.base_url = f"http://{env.get('SERVICE', 'home-assistant:8124')}"

        def run_analytics_config(self) -> dict:
            """
            runs the analytics config step of onboarding via the home assistant api
            """
            analytics_url = f"{self.base_url}/api/onboarding/analytics"
            print(f"We're going to post to {analytics_url} for core config finishing")

            response = requests.request("POST", analytics_url, headers=self.headers)
            print(response.text)

        def run_integration_config(self) -> dict:
            """
            runs the integration config step of onboarding via the home assistant api
            """
            integration_url = f"{self.base_url}/api/onboarding/integration"
            print(f"We're going to post to {integration_url} for core config finishing")

            response = requests.request("POST", integration_url, headers=self.headers)
            print(response.text)

        def run_core_config(self) -> dict:
            """
            runs the core config step of onboarding via the home assistant api
            """
            core_config_url = f"{self.base_url}/api/onboarding/core_config"
            print(f"We're going to post to {core_config_url} for core config finishing")

            response = requests.request("POST", core_config_url, headers=self.headers)
            print(response.text)

        def create_user(self) -> dict:
            """
            creates a user via the home assistant api
            """
            user_url = f"{self.base_url}/api/onboarding/users"
            print(f"We're going to post to {user_url} for user creation")

            payload = json.dumps({
              "client_id": self.base_url,
              "name": env.get('ADMIN_NAME', 'admin'),
              "username": env.get('ADMIN_USERNAME', 'admin'),
              "password": env.get('ADMIN_PASSWORD', 'test'),
              "language": env.get('ADMIN_LANGUAGE', 'en')
            })

            # this is the api request actually creates the new user and returns something like:
            # {"auth_code":"23456y7uiobgdfghjm54873hfjkdfghj"}
            response = requests.request("POST", user_url, headers=self.headers, data=payload)

            # update the headers to include the authorization token
            token = response.json()["auth_code"]
            print(token)
            self.headers['Authorization'] = f"auth_code {token}"
            self.headers.pop('Content-Type')


    if __name__ == '__main__':
        onboarding_obj = RunHomeAssistantOnboarding()
        onboarding_obj.create_user()
        onboarding_obj.run_core_config()
        onboarding_obj.run_integration_config()
        onboarding_obj.run_analytics_config()
{{- end }}
