{{- if and .Values.homeAssistant.owner.create (not .Values.homeAssistant.owner.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}-owner
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
data:
  ADMIN_NAME: {{ .Values.homeAssistant.owner.name | b64enc | quote }}
  ADMIN_USERNAME: {{ .Values.homeAssistant.owner.username | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.homeAssistant.owner.password | b64enc | quote }}
  ADMIN_LANGUAGE: {{ .Values.homeAssistant.owner.language | b64enc | quote }}
  {{- if .Values.homeAssistant.owner.externalURL }}
  EXTERNAL_URL: {{ .Values.homeAssistant.owner.externalURL | b64enc | quote }}
  {{- end }}
{{- end }}
