apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "home-assistant.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "home-assistant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and (or .Values.homeAssistant.configuration .Values.homeAssistant.existingConfigurationConfigMap) .Values.persistence.enabled }}
      initContainers:
        - name: config-creation
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - |
              cp /configYaml/configuration.yaml /config && \
              cp /configYaml/themes.yaml /config || touch /config/themes.yaml && \
              cp /configYaml/automations.yaml /config || touch /config/automations.yaml && \
              cp /configYaml/scenes.yaml /config || touch /config/scenes.yaml
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-yaml
              mountPath: /configYaml
            {{- if or .Values.homeAssistant.themes .Values.homeAssistant.existingThemesConfigMap }}
            - name: themes-yaml
              mountPath: /configYaml
            {{- end }}
            {{- if or .Values.homeAssistant.automations .Values.homeAssistant.existingAutomationsConfigMap }}
            - name: automations-yaml
              mountPath: /configYaml
            {{- end }}
            {{- if or .Values.homeAssistant.scenes .Values.homeAssistant.existingScenesConfigMap }}
            - name: scenes-yaml
              mountPath: /configYaml
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.persistence.enabled .Values.extraVolumeMounts }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: config
              mountPath: /config
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- end }}
      {{- if or .Values.persistence.enabled .Values.extraVolumes }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "home-assistant.name" . }}{{- end }}
      {{- end }}
      {{- if or .Values.homeAssistant.existingConfigurationConfigMap .Values.homeAssistant.configuration }}
        - name: config-yaml
          configMap:
            name: {{ if .Values.existingConfigurationConfigMap }}{{ .Values.homeAssistant.existingConfigurationConfigMap }}{{- else }}{{ include "home-assistant.name" . }}{{- end }}
      {{- end }}
      {{- if or .Values.homeAssistant.existingThemesConfigMap .Values.homeAssistant.themes }}
        - name: themes-yaml
          configMap:
            name: {{ if .Values.existingThemesConfigMap }}{{ .Values.homeAssistant.existingThemesConfigMap }}{{- else }}{{ include "home-assistant.name" . }}-themes{{- end }}
      {{- end }}
      {{- if or .Values.homeAssistant.existingAutomationsConfigMap .Values.homeAssistant.automations }}
        - name: automation-yaml
          configMap:
            name: {{ if .Values.existingAutomationsConfigMap }}{{ .Values.homeAssistant.existingAutomationsConfigMap }}{{- else }}{{ include "home-assistant.name" . }}-automations{{- end }}
      {{- end }}
      {{- if or .Values.homeAssistant.existingScenesConfigMap .Values.homeAssistant.scenes }}
        - name: scenes-yaml
          configMap:
            name: {{ if .Values.existingScenesConfigMap }}{{ .Values.homeAssistant.existingScenesConfigMap }}{{- else }}{{ include "home-assistant.name" . }}-scenes{{- end }}
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
